version: '3.7'

services:

  prod:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - '5432:5432'
    volumes:
      - postgres-volume:/var/lib/postgresql/data
      - ./source/dividido:/docker-entrypoint-initdb.d

volumes:
  postgres-volume:

