version: '3.7'

services:

  prod:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - '5432:5432'
    volumes:
      - postgres-volume:/var/lib/postgresql/data
      - ./source/dividido:/docker-entrypoint-initdb.d

    command: >
      sh -c "docker cp ./import_data.sh postgres:/ && docker exec -it postgres /bin/bash -c '/import_data.sh'"

volumes:
  postgres-volume:

